### ISSUE TITLE
Support for scala.collection.Seq

### ISSUE THREAD

**Issue by wajda** [arangodb/java-velocypack-module-scala#6]
velocypack-module-scala:1.0.4 doesn't support Scala ser/deserialization for `Seq`

**Comment by wajda** [comment]
Pull request created. Could you please take a look? - #5

**Comment by wajda** [comment]
Hey guys, it there any update on this? The PR was created quite a long time ago. Thank you.

**Comment by rashtao** [comment]
fixed in https://github.com/arangodb/java-velocypack-module-scala/pull/5
