### ISSUE TITLE
Scala maps support

### ISSUE THREAD

**Issue by wajda** [arangodb/java-velocypack-module-scala#8]
Currently `velocypack-module-scala` only supports immutable Map up to the size of 4.
Basically only the types `EmptyMap`, `Map1`, `Map2`, `Map3` and `Map4` are serialized correctly.
Other maps (e.g. `HashMap`, `TrieMap`, `TreeMap`, `ListMap` etc) aren't supported.

**Comment by wajda** [comment]
I'll send a PR for this one and #9 later today.
I think I'll do both things in one PR as the fixes aren't big to split them, and they have some stuff in common.

**Comment by rashtao** [comment]
fixed in https://github.com/arangodb/java-velocypack-module-scala/pull/11

**Comment by wajda** [comment]
Hi @rashtao
Has 1.2.0 been deployed to Maven Central?
It doesn't seem to be found there - https://repo1.maven.org/maven2/com/arangodb/velocypack-module-scala_2.12/1.2.0/velocypack-module-scala_2.12-1.2.0.pom

**Comment by rashtao** [comment]
Sorry @wajda , the deployment failed, redeploying now...
